[theme]
primaryColor = '#FF6347'  # Tomato color
backgroundColor = '#2E2E2E'  # Dark Gray
secondaryBackgroundColor = '#3A3A3A'  # Slightly lighter Dark Gray
textColor = '#FFFFFF'  # White
accentColor = '#FFD700'  # Gold
font = "monospace"
